### ISSUE TITLE
Some E3SM simulations run out of I/O decsriptor ids

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#449]
@singhbalwinder reported this issue. Some E3SM simulations (when satellite tracking option is enabled in E3SM v2) he has been working with abort with the following error message

```
Initializing of PIO decomposition failed. Maximum number of ioids (limit 65536) has been reached
```
This is due to the internal limit set for the maximum number of I/O descriptor ids inside SCORPIO. We need to start looking at reclaiming this descriptor space or expanding it to accommodate long running simulations that create many I/O decompositions.

(Note: We have not hit this limit with E3SM production simulations or other long running simulations before)

**Comment by rljacob** [comment]
I'd like to know more about this use case.  Why so many files getting opened?

**Comment by singhbalwinder** [comment]
@yshi5 has been running a simulation with `&satellite_options_nl` namelist option. She mentioned the following in one of her emails:
```
The simulation ran well before the start date of the satellite track. 
But after it started to do satellite output, the simulation became obviously 
slowly and crashed after several days.
```
The error message in `e3sm.log.*` was:

![image](https://user-images.githubusercontent.com/8136848/146276668-083ee0a5-8dac-45e1-97f5-c114242ae388.png)


So, it might be an issue in the code which are doing I/O for satellites.

**Comment by rljacob** [comment]
If there's not a logical reason why it would open 65K files, it should probably be looked at.

**Comment by jayeshkrishna** [comment]
The simulation is most likely creating many I/O decompositions (creating and destroying it, but creating many)

**Comment by jayeshkrishna** [comment]
@singhbalwinder as we discussed offline you or @yshi5 can keep track of the pio_initdecomp() calls in the code (count the number of calls to pio_initdecomp() and see if it makes sense) to find the cause of this overflow of ids.

**Comment by rljacob** [comment]
What causes the creation of an io decomposition?  I thought it was one for every open file.

**Comment by jayeshkrishna** [comment]
You can reuse I/O decompositions across files, the issue here could be that instead of reusing I/O decompositions it gets created/freed multiple times (even though the decompositions are freed and the simulation might not be using ~64K decompositions at the same time, ~64K calls to initdecomp results in hitting the upper limit on the id).

**Comment by yshi5** [comment]
Following the suggestion from @singhbalwinder and @jayeshkrishna, I have increased the number for PIO_IODESC_MAX_IDS in externals/scorpio/src/clib/pio.h. It is increased from 65536 to 128000. The model got integrated for a few more days, but still crashed with a similar error in e3sm.log*:

.......

1185: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 293: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 228: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 128: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 577: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 193: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 516: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 164: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
  65: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 640: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)
 609: PIO: FATAL ERROR: Aborting... An error occured, Initializing the PIO decomposition failed. Maximum number of ioids (limit = 128000) has been reached. err=-501. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u1/y/yshi/model/E3SM-v2.0.0-20211208/externals/scorpio/src/clib/pioc.c: 767)

.......

   0: Rank 0 [Wed Dec 22 20:43:04 2021] [c2-1c0s5n0] application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
  14: forrtl: error (76): Abort trap signal
  14: Image              PC                Routine            Line        Source
  14: e3sm.exe           0000000004FFC1D4  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000004CD5E80  Unknown               Unknown  Unknown
  14: e3sm.exe           000000000515FA50  Unknown               Unknown  Unknown
  14: e3sm.exe           00000000055B57E1  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000004E0ADB2  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000004DD884B  Unknown               Unknown  Unknown
  14: e3sm.exe           00000000039197CE  Unknown               Unknown  Unknown
  14: e3sm.exe           000000000391C229  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000003925E11  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000003870FB4  piolib_mod_mp_pio         599  piolib_mod.F90
  14: e3sm.exe           000000000056832A  sat_hist_mp_dump_         570  sat_hist.F90
  14: e3sm.exe           00000000005606BC  sat_hist_mp_sat_h         486  sat_hist.F90
  14: e3sm.exe           00000000005145CD  cam_history_mp_ws        4666  cam_history.F90
  14: e3sm.exe           0000000000502291  cam_comp_mp_cam_r         390  cam_comp.F90
  14: e3sm.exe           00000000004F50FE  atm_comp_mct_mp_a         579  atm_comp_mct.F90
  14: e3sm.exe           0000000000425B99  component_mod_mp_         751  component_mod.F90
  14: e3sm.exe           0000000000404B51  cime_comp_mod_mp_        3077  cime_comp_mod.F90
  14: e3sm.exe           000000000042578D  MAIN__                    153  cime_driver.F90
  14: e3sm.exe           0000000000401F72  Unknown               Unknown  Unknown
  14: e3sm.exe           00000000055ABD8F  Unknown               Unknown  Unknown
  14: e3sm.exe           0000000000401E5A  Unknown               Unknown  Unknown

.......

**Comment by jayeshkrishna** [comment]
Thanks for the update. This certainly looks like a different usage pattern than the regular model runs. I will take a look at it.

**Comment by rljacob** [comment]
There has to be a bug in how this option is handling files.

**Comment by rljacob** [comment]
@yshi5 please share in a comment here the block of  &satellite_options_nl you are using.

**Comment by yshi5** [comment]
The namelist I used:

&satellite_options_nl
 sathist_track_infile   = '/global/homes/y/yshi/data/Flight_track/McMurdo_track_20151201_20161231.nc'
 sathist_fincl          = 'PS', 'Z3', 'FICE', 'Q', 'T', 'U', 'V', 'WSUB', 'RELHUM', 'RHW', 'RHI', 'OMEGA', 'WSUBI', 'PSL',
                            'AODVIS',          'NUMIMM10sBC',         'NUMIMM10sDST',     'CCN3',
                     'H2SO4_sfnnuc1',       'num_a2_sfnnuc1',       'so4_a2_sfnnuc1',
                          'dgnd_a01', 'dgnd_a02', 'dgnd_a03', 'dgnd_a04',
                          'dgnw_a01', 'dgnw_a02', 'dgnw_a03', 'dgnw_a04',
                            'num_a1',   'num_a2',   'num_a3',   'num_a4',
                            'num_c1',   'num_c2',   'num_c3',   'num_c4',
                            'wat_a1',   'wat_a2',   'wat_a3',   'wat_a4',
                            'so4_a1',   'pom_a1',   'soa_a1',    'bc_a1',   'ncl_a1',   'mom_a1',   'dst_a1',
                            'so4_a2',   'soa_a2',   'ncl_a2',   'mom_a2',
                            'so4_a3',   'pom_a3',   'soa_a3',    'bc_a3',   'ncl_a3',   'mom_a3',   'dst_a3',
                            'pom_a4',    'bc_a4',   'mom_a4',
                            'so4_c1',   'pom_c1',   'soa_c1',    'bc_c1',   'ncl_c1',   'mom_c1',   'dst_c1',
                            'so4_c2',   'soa_c2',   'ncl_c2',   'mom_c2',
                            'so4_c3',   'pom_c3',   'soa_c3',    'bc_c3',   'ncl_c3',   'mom_c3',   'dst_c3',
                            'pom_c4',    'bc_c4',   'mom_c4',
                            'NUMICE',   'NUMLIQ',   'NUMSNO',   'NUMRAI',    'ICINC',    'ICWNC',     'AWNI',    'AWNC',
                            'ACTREL',   'ACTREI',    'ACTNI',    'ACTNL',     'FCTI',     'FCTL',
                            'CLDLIQ',   'CLDICE',   'AQSNOW',   'AQRAIN',      'LWC',      'IWC',
                             'QSNOW',    'NSNOW',   'SNOWQM',   'RAINQM',   'CDNUMC',
                              'AREL',     'AREI',   'ADSNOW',   'ADRAIN',   'RERCLD',
                             'CLOUD',   'CLDTOT',   'CLDLOW',   'CLDMED',   'CLDHGH',   'CONCLD',     'LWCF',     'SWCF',
                             'PRECC',    'PRECL',    'PRECT',
                          'TGCLDLWP', 'TGCLDIWP', 'TGCLDCWP',
                             'FREQL',    'FREQI',    'FREQS',    'FREQR',
                              'PRCO',     'PRAO',    'QVRES',    'CMFDT',    'CMFDQ',
                          'EVAPPREC', 'EVAPSNOW',  'CMFDLIQ',  'CMFDICE',
                              'FLNS',     'FSNS',     'FSNT',     'FLNT',    'SOLIN',
                              'FLDS',     'FLUT',   'FSUTOA',
                               'FDL',     'FDLC',      'FDS',     'FDSC',   'FLN200',
                   'ICE_ICLD_VISTAU',     'SNOW_ICLD_VISTAU',      'LIQ_ICLD_VISTAU',
                    'TOT_CLD_VISTAU',      'TOT_ICLD_VISTAU',     'EMIS',
                           'ICWMRST',  'ICIMRST',  'RHCFMIP',
                      'lambda_cloud', 'mu_cloud','dei_cloud'
 sathist_hfilename_spec = '%c.cam.AWARE.int_1min.%y-%m-%d-%s.nc'

**Comment by jayeshkrishna** [comment]
In sat_hist.F90 a decomposition is created/freed for every call to dump a column. So the optimal solution here would be to look whether a decomposition can be reused.
However SCORPIO should not fail for this case, so we will be adding a fix for this issue in SCORPIO (But to get good performance you will have to look at how these decompositions can be reused)

**Comment by jayeshkrishna** [comment]
@yshi5 / @singhbalwinder can you try out the SCORPIO changes in jayeshkrishna/rm_ub_on_ioids to see if it works for you?

```
cd <E3SM_SRC>/externals/scorpio
git fetch origin
git checkout jayeshkrishna/rm_ub_on_ioids

# The SCORPIO source is now updated to the branch above,
# Go ahead and build the E3SM case using create_newcase/case.build/case.submit
```

(PS: Sorry about the delay, but we decided to go ahead and fix this issue for the general issues with ioid limit rather than fixing it for just this issue)

**Comment by singhbalwinder** [comment]
I have never run any simulation with `satellite_options_nl` turned on. I am not sure if @yshi5 got it to work.

**Comment by rljacob** [comment]
The above discussion implied that it worked except for the I/O issues.

**Comment by rljacob** [comment]
@dqwu or @jayeshkrishna please add above to your queue.
